name: Feature Request
description: Suggest a new feature
labels: ["feature-request"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the feature you'd like
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: What problem does this solve?
    validations:
      required: true
