name: Restore Build Cache
description: Restore install and build output from cache

inputs:
  node-version:
    description: Node.js version
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/restore_install_cache
      with:
        node-version: ${{ inputs.node-version }}
    - name: Restore build output
      uses: actions/cache/restore@v4
      with:
        path: |
          packages/*/lib
          packages/*/tsconfig.tsbuildinfo
        key: ${{ runner.os }}-build-${{ inputs.node-version }}-${{ github.sha }}
        fail-on-cache-miss: true
