name: Setup Node
description: Setup Node.js with cache

inputs:
  node-version:
    description: Node.js version
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
